sudo: required
language: generic 
services: 
    - docker

before_install:
    - docker build -t marcosantarcangelo/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true marcosantarcangelo/react-test npm test

after_success:
    - docker build -t marcosantarcangelo/multi-client ./client
    - docker build -t marcosantarcangelo/multi-nginx ./nginx
    - docker build -t marcosantarcangelo/multi-server ./server
    - docker build -t marcosantarcangelo/multi-worker ./worker
    # Log into the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push marcosantarcangelo/multi-client
    - docker push marcosantarcangelo/multi-nginx
    - docker push marcosantarcangelo/multi-server
    - docker push marcosantarcangelo/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-330189939975
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY